# This is a basic workflow to help you get started with Actions

name: manual-approve

on:
  workflow_dispatch:

jobs:
  echo-job:
    runs-on: ubuntu-latest
    environment: 'SIT'

    steps:
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
