# This is a basic workflow to help you get started with Actions

name: manual-approve

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest    
    steps:
      - name: deploy
        run: |
          echo Deploy APP
  
  deploy-job:
    needs: build
    runs-on: ubuntu-latest
    environment: 'SIT'

    steps:
      - name: deploy
        run: |
          echo Deploy APP
